name: 'project1_sales_analytics'
version: '1.0'
config-version: 2

profile: 'user'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  project1_sales_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
