{{ config(materialized = 'table') }}

select
    CUSTOMER_ID,
    CHATBOT_USAGE_COUNT,
    LAST_CHATBOT_INTERACTION,
    EMAIL_OPENED_COUNT,
    CLICKED_AD_CAMPAIGNS,
    PARTICIPATED_IN_SURVEY,
    PREFERRED_CHANNEL,
    LOYALTY_PROGRAM_STATUS,
    MARKETING_RESPONSIVENESS,
    REFERRAL_LIKELIHOOD,
    GENDER,
    TENURE_MONTHS,
    TOTAL_TRANSACTIONS,
    TOTAL_UNITS_PURCHASED,
    TOTAL_SPEND,
    AVG_RATING,
    FIRST_PURCHASE_DATE,
    LAST_PURCHASE_DATE
from {{ ref('fct_customer_metrics') }}
